### ISSUE TITLE
合并查询问题

### ISSUE THREAD

**Issue by lable** [overtly/core-data#3]
如果使用时间做为表名规则，写数据应该没有问题，但是跨天的临界点后就可能出现数据查询不到的问题。比如微信支付，支付结果回写的时候可能跨过了时间点。

        public override Func<string> TableNameFunc => () =>
        {
            var tableName = $"{GetMainTableName()}_{DateTime.Now.ToString("yyyyMMdd")}";
            return tableName;
        };

**Comment by mojinxun** [comment]
这个就是业务上的兼容啦，不同的业务采用不同的分表模式，完全自定义。
另外针对你说的这种，可以在业务查询的时候，在一定时间区间内，同时查询前一天的数据，或者订单号上进行解析等等，有很多种方式
