### ISSUE TITLE
建议修正一个方法

### ISSUE THREAD

**Issue by taozengyu** [overtly/core-data#5]
CheckTableIfMissingCreate此方法在判定TableNameFunc方法不存在的情况下，建议自动获取一下表名，这样普通继承的仓储类就没必要必须实现CheckTableIfMissingCreate和CreateScriptFunc；例如修改为下面这样：
   public static bool CheckTableIfMissingCreate<T>(this IBaseRepository<T> repository, bool isMaster)
            where T : class, new()
        {
            var tableName = repository.TableNameFunc?.Invoke();
            if (string.IsNullOrEmpty(tableName))
                tableName = repository.GetMainTableName();
            var createScript = repository.CreateScriptFunc?.Invoke(tableName);
            if (string.IsNullOrEmpty(createScript))
                return true;

            var tableKey = $"{repository.DbStoreKey}_{tableName}_{isMaster}";
            var existTable = ExistInformation.GetOrAdd(tableKey, k => repository.IsExistTable(tableName, isMaster));
            if (!existTable)
            {
                ExistInformation.TryRemove(tableKey, out existTable);
                if (!isMaster)
                    return false;

                try
                {
                    using (var connection = repository.OpenConnection(true, true))
                    {
                        connection.ExecuteAsync(createScript).GetAwaiter().GetResult();
                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            return true;
        }

**Comment by mojinxun** [comment]
你拉个分支，合并过来，我看一下

**Comment by mojinxun** [comment]
暂时关闭
